# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cocogold',
                'doc_host': 'https://pcuenca.github.io',
                'git_url': 'https://github.com/pcuenca/cocogold',
                'lib_path': 'cocogold'},
  'syms': {'cocogold.core': {'cocogold.core.foo': ('core.html#foo', 'cocogold/core.py')}}}
